project:
  type: website

website:
  title: "Home"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ruxandra2ichim
format:
  html:
    theme: slate
    css: styles.css



